### ISSUE TITLE
builder

### ISSUE THREAD

**Issue by rtgtgth** [ScRiPt1337/blackhole-ransomware#7]
Hello, why can't you open your builder? There seems to be something wrong with it. Please have a look. Thank you.
[blackhole-ransomware-master.zip](https://github.com/ScRiPt1337/blackhole-ransomware/files/5917496/blackhole-ransomware-master.zip)

**Comment by acheong08** [comment]
@rtgtgth Because this whole this is a fucking scam lol

**Comment by ScRiPt1337** [comment]
> @rtgtgth Because this whole this is a fucking scam lol

okay lol
